# Generated by Django 5.2.1 on 2025-06-03 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_remove_assignment_course_remove_content_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'faculty'}, related_name='programs_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
